##SUBDIRS = class  dynamic  file_op  interrupt  interrupt1  ioctal  sample  sample_mkdev
all : 
	cd class && $(MAKE)
	cd dynamic && $(MAKE)
	cd file_op && $(MAKE)
	cd interrupt && $(MAKE)
	cd interrupt1 && $(MAKE)
	cd ioctal && $(MAKE)
	cd sample && $(MAKE)
	cd sample_mkdev && $(MAKE)
clean:
	cd class && $(MAKE) clean
	cd dynamic && $(MAKE) clean
	cd file_op && $(MAKE) clean
	cd interrupt && $(MAKE) clean
	cd interrupt1 && $(MAKE) clean
	cd ioctal && $(MAKE) clean
	cd sample && $(MAKE) clean
	cd sample_mkdev && $(MAKE) clean
